### ISSUE TITLE
Sample does not work

### ISSUE THREAD

**Issue by aducom** [Alexey-T/ATSynEdit_Cmp#2]
I downloaded and installed from git the full atsynedit package. The sample provided with atsynedit_cmp does not compile:

TATEditorCommandInvoke is not found, replaced it by TATCommandInvoke, but...
cInvokeAppInternal is not found. Could not find something in the code. I managed to compile it by using TATCommandInvoke.AppInternal. However the popup is very small, unreadable (on a 2k screen)
I debugged a bit deeper and found that the listboxdrawitem rect is set to 0,0,490,2 A rect of 2 px is a bit small ;-)
The problem does also occur on 1080p. Not sure how to proceed, as I can't seem to find why the height is reported wrong.
If I set the autosize of the form, then The panel is a bit larger, but only shows part of the dialog. 
Showstopper here unfortunately. ;-)

**Comment by Alexey-T** [comment]
thanks for report!
I fixed the type (Invoke) and fixed too small listbox (MonoFontSize prop was not inited in ATFlatControls - update ATFlatControls from Git).

**Comment by aducom** [comment]
Unfortunately, it is not fixed completely. I do see a scroll box now, but there are no items. It seems that the Rect in the listboxdrawitem event is set to 0,0,0,22, so a width of 0...
Sorry, I mixed atsynedit with the online-package manager. I deleted atsynedit and reinstalled from git, and all seems to be ok now. Thnx, for your fast response.

**Comment by Alexey-T** [comment]
yes, I change only GIT version!
